checks:
  php:
    code_rating: true
tools:
    external_code_coverage:
        timeout: 1800
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        enabled: false
    php_cpd:
        enabled: true
        excluded_dirs: ["tests", "vendor", "examples"]
    php_cs_fixer:
        enabled: false
    php_loc:
        enabled: true
        excluded_dirs: ["tests", "vendor", "examples"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["tests", "vendor", "examples"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*"]
    php_hhvm:
        enabled: false