sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 7
      env:
        - EXECUTE_CS_CHECK=true
    - php: hhvm
  allow_failures:
      - php: hhvm

install:
  - travis_retry composer install --no-interaction

script:
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi